/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.automation.server;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Server {
    public static void main(String[] args) {
		SpringApplication.run(Server.class, args);
	}
}
