/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.automationtest.cli;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private final static Logger logger = LoggerFactory.getLogger("cli");

    public static void main(String[] args) {
        logger.info("cli starting ...");
        handle(args);
        logger.info("cli finished.");
    }

    public static void handle(String[] args) {
        // TODO: logic
        
    }
}
