/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.automationtest.cli;

import com.github.rvesse.airline.annotations.Cli;
import com.github.rvesse.airline.help.Help;

@Cli(name = "automation test cli", description = "automation test client tool", 
defaultCommand = Help.class , commands = {Help.class, RunSuite.class})
public class App {

    public static void main(String[] args) {
        handle(args);
    }

    public static void handle(String[] args) {
        com.github.rvesse.airline.Cli<Runnable> cli = new com.github.rvesse.airline.Cli<>(App.class);
        try{
            Runnable cmd = cli.parse(args);
            cmd.run();
        } catch(Exception e) {
            System.out.println(e.getMessage());
        }
        
    }
}
