@startuml

title  Components

package "Extension" {
    component [Chrome Extension] as Ext
}

package "Front End" {
    component [React Hooks] as GUI
}

package "Client" as Cli {
    component [docker] as Docker
}

cloud "Rest API" as Internet {
}

package "Server" as Server {
    [File Service] as FS
    [Git Access] as GA

}

database "Git Repository\n" as Repo {
    [Test Suites]
    [Test Cases]
    [UI Objects]
    [Data]
}

Ext -down-> Repo
Docker -down-> FS
Docker .down. Repo
GUI -down-> Internet
Internet -down-> Server
GA .right. Repo

@enduml